apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skype
  namespace: skype
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skype
    spec:
      containers:
      - name: skype
        image: aliayubkhan/susi_skypebot:latest
        imagePullPolicy: Always
        env: 
        - name: appID
          value: "5d336a42-124a-4b79-bbbe-788998da27a1"
        - name: appPassword
          value: "E3HrKEmYkiYTiE0eQCYAnbh"
        ports:
        - containerPort: 8080

