apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skype
  namespace: skype
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skype
    spec:
      containers:
      - name: skype
        image: fossasia/susi_skypebot:latest-master
        imagePullPolicy: Always
        env: 
        - name: appId
          value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        - name: appPassword
          value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        ports:
        - containerPort: 8080

