apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: skype
  namespace: skype
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - susi-skype.tk
    secretName: skype-tls
  rules:
  - host: susi-skype.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: skype
          servicePort: 80
